document.addEventListener("DOMContentLoaded",loadTable);
$(document).ready(function(){restore_options();var a=$("#coinselect");$(a).select2({placeholder:"Choose currencies to watch",allowClear:!0,data:[{id:"BTC",text:"Bitcoin"},{id:"ETH",text:"Ethereum"},{id:"LTC",text:"Litecoin"},{id:"BCH",text:"Bitcoin Cash"},{id:"XRP",text:"Ripple"},{id:"ACT",text:"Achain"},{id:"AEON",text:"Aeon"},{id:"ARK",text:"Ark"},{id:"XAS",text:"Asch"},{id:"BAY",text:"BitBay"},{id:"BTG",text:"Bitcoin Gold"},{id:"BTCD",text:"BitcoinDark"},{id:"BCC",text:"BitConnect"},{id:"BTX",
text:"Bitcore"},{id:"BTS",text:"BitShares"},{id:"BLOCK",text:"Blocknet"},{id:"BCO",text:"BridgeCoin"},{id:"BURST",text:"Burst"},{id:"GBYTE",text:"Byteball Bytes"},{id:"BCN",text:"Bytecoin"},{id:"ADA",text:"Cardano"},{id:"CLOAK",text:"CloakCoin"},{id:"XCP",text:"Counterparty"},{id:"CRW",text:"Crown"},{id:"CNX",text:"Cryptonex"},{id:"DASH",text:"Dash"},{id:"DCT",text:"DECENT"},{id:"DCR",text:"Decred"},{id:"DGB",text:"DigiByte"},{id:"XDN",text:"DigitalNote"},{id:"DIME",text:"Dimecoin"},{id:"DOGE",text:"Dogecoin"},
{id:"ECC",text:"ECC"},{id:"EMC2",text:"Einsteinium"},{id:"ECA",text:"Electra"},{id:"ETN",text:"Electroneum"},{id:"EMC",text:"Emercoin"},{id:"EOS",text:"EOS"},{id:"ETC",text:"Ethereum Classic"},{id:"XP",text:"Experience Points"},{id:"FCT",text:"Factom"},{id:"FTC",text:"Feathercoin"},{id:"FLASH",text:"Flash"},{id:"GAME",text:"GameCredits"},{id:"GRS",text:"Groestlcoin"},{id:"NLG",text:"Gulden"},{id:"GXS",text:"GXShares"},{id:"THC",text:"HempCoin"},{id:"HSR",text:"Hshare"},{id:"HTML",text:"HTMLCOIN"},
{id:"IOC",text:"I/O Coin"},{id:"MIOTA",text:"IOTA"},{id:"KMD",text:"Komodo"},{id:"KCS",text:"KuCoin Shares"},{id:"LBC",text:"LBRY Credits"},{id:"LSK",text:"Lisk"},{id:"LKK",text:"Lykke"},{id:"ETP",text:"Metaverse ETP"},{id:"MNX",text:"MinexCoin"},{id:"MONA",text:"MonaCoin"},{id:"XMR",text:"Monero"},{id:"MOON",text:"Mooncoin"},{id:"NMC",text:"Namecoin"},{id:"NAV",text:"NAV Coin"},{id:"NEBL",text:"Neblio"},{id:"XEM",text:"NEM"},{id:"NEO",text:"NEO"},{id:"NXS",text:"Nexus"},{id:"NXT",text:"Nxt"},{id:"PAC",
text:"PACcoin"},{id:"PART",text:"Particl"},{id:"PPC",text:"Peercoin"},{id:"PIVX",text:"PIVX"},{id:"PURA",text:"Pura"},{id:"QTUM",text:"Qtum"},{id:"XRB",text:"RaiBlocks"},{id:"RDD",text:"ReddCoin"},{id:"RISE",text:"Rise"},{id:"SLS",text:"SaluS"},{id:"XSH",text:"SHIELD"},{id:"SHIFT",text:"Shift"},{id:"SC",text:"Siacoin"},{id:"SKY",text:"Skycoin"},{id:"SMART",text:"SmartCash"},{id:"XSPEC",text:"Spectrecoin"},{id:"STEEM",text:"Steem"},{id:"XLM",text:"Stellar"},{id:"STRAT",text:"Stratis"},{id:"SYS",text:"Syscoin"},
{id:"UBQ",text:"Ubiq"},{id:"VEN",text:"VeChain"},{id:"XVG",text:"Verge"},{id:"VTC",text:"Vertcoin"},{id:"VIA",text:"Viacoin"},{id:"VOX",text:"Voxels"},{id:"WAVES",text:"Waves"},{id:"XBY",text:"XTRABYTES"},{id:"ZEC",text:"Zcash"},{id:"ZCL",text:"ZClassic"},{id:"XZC",text:"ZCoin"},{id:"ZEN",text:"ZenCash"}],width:"100%",multiple:!0});$(a).change(function(b){var d=$("#watch-list").text();b=$(a).select2("data");var c=d.split(",");b.forEach(function(a){c.includes(a.id)||(d+=a.id+",")});$("#watch-list").text(d);
save_options()});$("#coinwatch").click(function(){console.log("row clicked");console.log(this.id)})});function formatCoin(a){return a.id?$('<i class="'+a.element.value+'"> '+a.text+"</i>"):a.text}
function loadTable(a){null==a&&(document.getElementById("status").textContent="Options saved.",a=[{mstCoinList:{symbol:"BTC",price:"$0",cssClass:"has-text-info",changePct:"0.0"}}]);var b=$("#charts").html();Mustache.parse(b);$("#watch-list").textContent+=a;a=Mustache.render(b,{mstCoinList:a});$("#spinner").hide();$("#target").html(a)}function removeCoin(a){console.log("removeCoin called")}
function restore_options(){chrome.storage.sync.get("currencies",function(a){chrome.runtime.error||($("#watch-list").text(a.currencies),fetchPrices(a.currencies))})}
function fetchPrices(a){null==a&&(a="ADA,EOS");var b=[];axios.get("https://min-api.cryptocompare.com/data/pricemultifull?tsyms=USD,CAD,CNY,EUR,GBP,INR,JPY,KWN&fsyms="+a).then(function(a){for(coin in a.data.RAW)b.push(a.data.RAW[coin]);a=[];for(var c=0;c<b.length;c++){var d=0<=b[c].USD.CHANGEPCT24HOUR?"has-text-success":"has-text-danger",e=b[c].USD.FROMSYMBOL,f=Number.parseFloat(b[c].USD.PRICE).toFixed(2),g=Number.parseFloat(b[c].USD.CHANGEPCT24HOUR).toFixed(2);a.push({symbol:e,price:f,cssClass:d,
changePct:g})}loadTable(a)})["catch"](function(a){console.log(a)})}function save_options(){var a=[$("#watch-list").text()];chrome.storage.sync.set({currencies:a},function(){fetchPrices(a)})};